[package]
name = "substrate-frame-rpc-support"
version = "2.0.0-rc5"
authors = ["Parity Technologies <admin@parity.io>", "Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate RPC for FRAME's support"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = { version = "0.3.0", features = ["compat"] }
jsonrpc-client-transports = { version = "15.0.0", default-features = false, features = ["http"], git = "https://github.com/paritytech/jsonrpc.git" }
jsonrpc-core = { version = "15.0.0", git = "https://github.com/paritytech/jsonrpc.git" }
codec = { package = "parity-scale-codec", version = "1.3.1" }
serde = "1"
frame-support = { version = "2.0.0-rc5", path = "../../../../frame/support" }
sp-storage = { version = "2.0.0-rc5", path = "../../../../primitives/storage" }
sc-rpc-api = { version = "0.8.0-rc5", path = "../../../../client/rpc-api" }

[dev-dependencies]
frame-system = { version = "2.0.0-rc5", path = "../../../../frame/system" }
tokio = "0.2"
