[package]
name = "sc-logging"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate CLI interface."
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-logging"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ansi_term = "0.12.1"
atty = "0.2.13"
lazy_static = "1.4.0"
regex = "1.4.2"
sc-telemetry = { version = "2.0.0", path = "../telemetry" }
sc-tracing = { version = "2.0.0", path = "../tracing" }
tracing = "0.1.19"
tracing-log = "0.1.1"
tracing-subscriber = "0.2.10"

[target.'cfg(target_os = "unknown")'.dependencies]
wasm-bindgen = "0.2.67"
web-sys = { version = "0.3.44", features = ["console"] }
